Check the issue

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -130,150 +130,150 @@ jobs:
         echo "::set-output name=required::$(cat required.json)"
 
   # Build: build Spark and run the tests for specified modules.
-  build:
-    name: "Build modules (${{ format('{0}, {1} job', needs.configure-jobs.outputs.branch, needs.configure-jobs.outputs.type) }}): ${{ matrix.modules }} ${{ matrix.comment }} (JDK ${{ matrix.java }}, ${{ matrix.hadoop }}, ${{ matrix.hive }})"
-    needs: [configure-jobs, precondition]
-    # Run scheduled jobs for Apache Spark only
-    # Run regular jobs for commit in both Apache Spark and forked repository
-    if: >-
-      (github.repository == 'apache/spark' && needs.configure-jobs.outputs.type == 'scheduled')
-      || (needs.configure-jobs.outputs.type == 'regular' && fromJson(needs.precondition.outputs.required).build == 'true')
-    # Ubuntu 20.04 is the latest LTS. The next LTS is 22.04.
-    runs-on: ubuntu-20.04
-    strategy:
-      fail-fast: false
-      matrix:
-        java:
-          - ${{ needs.configure-jobs.outputs.java }}
-        hadoop:
-          - ${{ needs.configure-jobs.outputs.hadoop }}
-        hive:
-          - hive2.3
-        # TODO(SPARK-32246): We don't test 'streaming-kinesis-asl' for now.
-        # Kinesis tests depends on external Amazon kinesis service.
-        # Note that the modules below are from sparktestsupport/modules.py.
-        modules:
-          - >-
-            core, unsafe, kvstore, avro,
-            network-common, network-shuffle, repl, launcher,
-            examples, sketch, graphx
-          - >-
-            catalyst, hive-thriftserver
-          - >-
-            streaming, sql-kafka-0-10, streaming-kafka-0-10,
-            mllib-local, mllib,
-            yarn, mesos, kubernetes, hadoop-cloud, spark-ganglia-lgpl
-        # Here, we split Hive and SQL tests into some of slow ones and the rest of them.
-        included-tags: [""]
-        excluded-tags: [""]
-        comment: [""]
-        include:
-          # Hive tests
-          - modules: hive
-            java: ${{ needs.configure-jobs.outputs.java }}
-            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
-            hive: hive2.3
-            included-tags: org.apache.spark.tags.SlowHiveTest
-            comment: "- slow tests"
-          - modules: hive
-            java: ${{ needs.configure-jobs.outputs.java }}
-            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
-            hive: hive2.3
-            excluded-tags: org.apache.spark.tags.SlowHiveTest
-            comment: "- other tests"
-          # SQL tests
-          - modules: sql
-            java: ${{ needs.configure-jobs.outputs.java }}
-            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
-            hive: hive2.3
-            included-tags: org.apache.spark.tags.ExtendedSQLTest
-            comment: "- slow tests"
-          - modules: sql
-            java: ${{ needs.configure-jobs.outputs.java }}
-            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
-            hive: hive2.3
-            excluded-tags: org.apache.spark.tags.ExtendedSQLTest
-            comment: "- other tests"
-    env:
-      MODULES_TO_TEST: ${{ matrix.modules }}
-      EXCLUDED_TAGS: ${{ matrix.excluded-tags }}
-      INCLUDED_TAGS: ${{ matrix.included-tags }}
-      HADOOP_PROFILE: ${{ matrix.hadoop }}
-      HIVE_PROFILE: ${{ matrix.hive }}
-      GITHUB_PREV_SHA: ${{ github.event.before }}
-      SPARK_LOCAL_IP: localhost
-    steps:
-    - name: Checkout Spark repository
-      uses: actions/checkout@v2
-      # In order to fetch changed files
-      with:
-        fetch-depth: 0
-        repository: apache/spark
-        ref: ${{ needs.configure-jobs.outputs.branch }}
-    - name: Sync the current branch with the latest in Apache Spark
-      if: github.repository != 'apache/spark'
-      run: |
-        echo "APACHE_SPARK_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
-        git fetch https://github.com/$GITHUB_REPOSITORY.git ${GITHUB_REF#refs/heads/}
-        git -c user.name='Apache Spark Test Account' -c user.email='sparktestacc@gmail.com' merge --no-commit --progress --squash FETCH_HEAD
-        git -c user.name='Apache Spark Test Account' -c user.email='sparktestacc@gmail.com' commit -m "Merged commit"
-    # Cache local repositories. Note that GitHub Actions cache has a 2G limit.
-    - name: Cache Scala, SBT and Maven
-      uses: actions/cache@v2
-      with:
-        path: |
-          build/apache-maven-*
-          build/scala-*
-          build/*.jar
-          ~/.sbt
-        key: build-${{ hashFiles('**/pom.xml', 'project/build.properties', 'build/mvn', 'build/sbt', 'build/sbt-launch-lib.bash', 'build/spark-build-info') }}
-        restore-keys: |
-          build-
-    - name: Cache Coursier local repository
-      uses: actions/cache@v2
-      with:
-        path: ~/.cache/coursier
-        key: ${{ matrix.java }}-${{ matrix.hadoop }}-coursier-${{ hashFiles('**/pom.xml', '**/plugins.sbt') }}
-        restore-keys: |
-          ${{ matrix.java }}-${{ matrix.hadoop }}-coursier-
-    - name: Install Java ${{ matrix.java }}
-      uses: actions/setup-java@v1
-      with:
-        java-version: ${{ matrix.java }}
-    - name: Install Python 3.8
-      uses: actions/setup-python@v2
-      # We should install one Python that is higher then 3+ for SQL and Yarn because:
-      # - SQL component also has Python related tests, for example, IntegratedUDFTestUtils.
-      # - Yarn has a Python specific test too, for example, YarnClusterSuite.
-      if: contains(matrix.modules, 'yarn') || (contains(matrix.modules, 'sql') && !contains(matrix.modules, 'sql-'))
-      with:
-        python-version: 3.8
-        architecture: x64
-    - name: Install Python packages (Python 3.8)
-      if: (contains(matrix.modules, 'sql') && !contains(matrix.modules, 'sql-'))
-      run: |
-        python3.8 -m pip install 'numpy>=1.20.0' pyarrow pandas scipy xmlrunner
-        python3.8 -m pip list
-    # Run the tests.
-    - name: Run tests
-      env: ${{ fromJSON(needs.configure-jobs.outputs.envs) }}
-      run: |
-        # Hive "other tests" test needs larger metaspace size based on experiment.
-        if [[ "$MODULES_TO_TEST" == "hive" ]] && [[ "$EXCLUDED_TAGS" == "org.apache.spark.tags.SlowHiveTest" ]]; then export METASPACE_SIZE=2g; fi
-        export SERIAL_SBT_TESTS=1
-        ./dev/run-tests --parallelism 1 --modules "$MODULES_TO_TEST" --included-tags "$INCLUDED_TAGS" --excluded-tags "$EXCLUDED_TAGS"
-    - name: Upload test results to report
-      if: always()
-      uses: actions/upload-artifact@v2
-      with:
-        name: test-results-${{ matrix.modules }}-${{ matrix.comment }}-${{ matrix.java }}-${{ matrix.hadoop }}-${{ matrix.hive }}
-        path: "**/target/test-reports/*.xml"
-    - name: Upload unit tests log files
-      if: failure()
-      uses: actions/upload-artifact@v2
-      with:
-        name: unit-tests-log-${{ matrix.modules }}-${{ matrix.comment }}-${{ matrix.java }}-${{ matrix.hadoop }}-${{ matrix.hive }}
-        path: "**/target/unit-tests.log"
+#  build:
+#    name: "Build modules (${{ format('{0}, {1} job', needs.configure-jobs.outputs.branch, needs.configure-jobs.outputs.type) }}): ${{ matrix.modules }} ${{ matrix.comment }} (JDK ${{ matrix.java }}, ${{ matrix.hadoop }}, ${{ matrix.hive }})"
+#    needs: [configure-jobs, precondition]
+#    # Run scheduled jobs for Apache Spark only
+#    # Run regular jobs for commit in both Apache Spark and forked repository
+#    if: >-
+#      (github.repository == 'apache/spark' && needs.configure-jobs.outputs.type == 'scheduled')
+#      || (needs.configure-jobs.outputs.type == 'regular' && fromJson(needs.precondition.outputs.required).build == 'true')
+#    # Ubuntu 20.04 is the latest LTS. The next LTS is 22.04.
+#    runs-on: ubuntu-20.04
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        java:
+#          - ${{ needs.configure-jobs.outputs.java }}
+#        hadoop:
+#          - ${{ needs.configure-jobs.outputs.hadoop }}
+#        hive:
+#          - hive2.3
+#        # TODO(SPARK-32246): We don't test 'streaming-kinesis-asl' for now.
+#        # Kinesis tests depends on external Amazon kinesis service.
+#        # Note that the modules below are from sparktestsupport/modules.py.
+#        modules:
+#          - >-
+#            core, unsafe, kvstore, avro,
+#            network-common, network-shuffle, repl, launcher,
+#            examples, sketch, graphx
+#          - >-
+#            catalyst, hive-thriftserver
+#          - >-
+#            streaming, sql-kafka-0-10, streaming-kafka-0-10,
+#            mllib-local, mllib,
+#            yarn, mesos, kubernetes, hadoop-cloud, spark-ganglia-lgpl
+#        # Here, we split Hive and SQL tests into some of slow ones and the rest of them.
+#        included-tags: [""]
+#        excluded-tags: [""]
+#        comment: [""]
+#        include:
+#          # Hive tests
+#          - modules: hive
+#            java: ${{ needs.configure-jobs.outputs.java }}
+#            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
+#            hive: hive2.3
+#            included-tags: org.apache.spark.tags.SlowHiveTest
+#            comment: "- slow tests"
+#          - modules: hive
+#            java: ${{ needs.configure-jobs.outputs.java }}
+#            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
+#            hive: hive2.3
+#            excluded-tags: org.apache.spark.tags.SlowHiveTest
+#            comment: "- other tests"
+#          # SQL tests
+#          - modules: sql
+#            java: ${{ needs.configure-jobs.outputs.java }}
+#            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
+#            hive: hive2.3
+#            included-tags: org.apache.spark.tags.ExtendedSQLTest
+#            comment: "- slow tests"
+#          - modules: sql
+#            java: ${{ needs.configure-jobs.outputs.java }}
+#            hadoop: ${{ needs.configure-jobs.outputs.hadoop }}
+#            hive: hive2.3
+#            excluded-tags: org.apache.spark.tags.ExtendedSQLTest
+#            comment: "- other tests"
+#    env:
+#      MODULES_TO_TEST: ${{ matrix.modules }}
+#      EXCLUDED_TAGS: ${{ matrix.excluded-tags }}
+#      INCLUDED_TAGS: ${{ matrix.included-tags }}
+#      HADOOP_PROFILE: ${{ matrix.hadoop }}
+#      HIVE_PROFILE: ${{ matrix.hive }}
+#      GITHUB_PREV_SHA: ${{ github.event.before }}
+#      SPARK_LOCAL_IP: localhost
+#    steps:
+#    - name: Checkout Spark repository
+#      uses: actions/checkout@v2
+#      # In order to fetch changed files
+#      with:
+#        fetch-depth: 0
+#        repository: apache/spark
+#        ref: ${{ needs.configure-jobs.outputs.branch }}
+#    - name: Sync the current branch with the latest in Apache Spark
+#      if: github.repository != 'apache/spark'
+#      run: |
+#        echo "APACHE_SPARK_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
+#        git fetch https://github.com/$GITHUB_REPOSITORY.git ${GITHUB_REF#refs/heads/}
+#        git -c user.name='Apache Spark Test Account' -c user.email='sparktestacc@gmail.com' merge --no-commit --progress --squash FETCH_HEAD
+#        git -c user.name='Apache Spark Test Account' -c user.email='sparktestacc@gmail.com' commit -m "Merged commit"
+#    # Cache local repositories. Note that GitHub Actions cache has a 2G limit.
+#    - name: Cache Scala, SBT and Maven
+#      uses: actions/cache@v2
+#      with:
+#        path: |
+#          build/apache-maven-*
+#          build/scala-*
+#          build/*.jar
+#          ~/.sbt
+#        key: build-${{ hashFiles('**/pom.xml', 'project/build.properties', 'build/mvn', 'build/sbt', 'build/sbt-launch-lib.bash', 'build/spark-build-info') }}
+#        restore-keys: |
+#          build-
+#    - name: Cache Coursier local repository
+#      uses: actions/cache@v2
+#      with:
+#        path: ~/.cache/coursier
+#        key: ${{ matrix.java }}-${{ matrix.hadoop }}-coursier-${{ hashFiles('**/pom.xml', '**/plugins.sbt') }}
+#        restore-keys: |
+#          ${{ matrix.java }}-${{ matrix.hadoop }}-coursier-
+#    - name: Install Java ${{ matrix.java }}
+#      uses: actions/setup-java@v1
+#      with:
+#        java-version: ${{ matrix.java }}
+#    - name: Install Python 3.8
+#      uses: actions/setup-python@v2
+#      # We should install one Python that is higher then 3+ for SQL and Yarn because:
+#      # - SQL component also has Python related tests, for example, IntegratedUDFTestUtils.
+#      # - Yarn has a Python specific test too, for example, YarnClusterSuite.
+#      if: contains(matrix.modules, 'yarn') || (contains(matrix.modules, 'sql') && !contains(matrix.modules, 'sql-'))
+#      with:
+#        python-version: 3.8
+#        architecture: x64
+#    - name: Install Python packages (Python 3.8)
+#      if: (contains(matrix.modules, 'sql') && !contains(matrix.modules, 'sql-'))
+#      run: |
+#        python3.8 -m pip install 'numpy>=1.20.0' pyarrow pandas scipy xmlrunner
+#        python3.8 -m pip list
+#    # Run the tests.
+#    - name: Run tests
+#      env: ${{ fromJSON(needs.configure-jobs.outputs.envs) }}
+#      run: |
+#        # Hive "other tests" test needs larger metaspace size based on experiment.
+#        if [[ "$MODULES_TO_TEST" == "hive" ]] && [[ "$EXCLUDED_TAGS" == "org.apache.spark.tags.SlowHiveTest" ]]; then export METASPACE_SIZE=2g; fi
+#        export SERIAL_SBT_TESTS=1
+#        ./dev/run-tests --parallelism 1 --modules "$MODULES_TO_TEST" --included-tags "$INCLUDED_TAGS" --excluded-tags "$EXCLUDED_TAGS"
+#    - name: Upload test results to report
+#      if: always()
+#      uses: actions/upload-artifact@v2
+#      with:
+#        name: test-results-${{ matrix.modules }}-${{ matrix.comment }}-${{ matrix.java }}-${{ matrix.hadoop }}-${{ matrix.hive }}
+#        path: "**/target/test-reports/*.xml"
+#    - name: Upload unit tests log files
+#      if: failure()
+#      uses: actions/upload-artifact@v2
+#      with:
+#        name: unit-tests-log-${{ matrix.modules }}-${{ matrix.comment }}-${{ matrix.java }}-${{ matrix.hadoop }}-${{ matrix.hive }}
+#        path: "**/target/unit-tests.log"
 
   pyspark:
     needs: [configure-jobs, precondition]
@@ -531,7 +531,6 @@ jobs:
         #   See also https://issues.apache.org/jira/browse/SPARK-35375.
         python3.9 -m pip install 'sphinx<3.1.0' mkdocs pydata_sphinx_theme ipython nbsphinx numpydoc 'jinja2<3.0.0'
         python3.9 -m pip install sphinx_plotly_directive 'numpy>=1.20.0' pyarrow pandas 'plotly>=4.8'
-        python3.9 -m pip install markupsafe==2.0.1
         apt-get update -y
         apt-get install -y ruby ruby-dev
         Rscript -e "install.packages(c('devtools', 'testthat', 'knitr', 'rmarkdown', 'roxygen2'), repos='https://cloud.r-project.org/')"
